services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile
    image: nextjs-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--header", "Accept: application/json", "-O", "-", "http://localhost:3000/api/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
